### ISSUE TITLE
check that theta is not nan before passing to tomopy recon

### ISSUE THREAD

**Issue by perlmutter** [samwelborn/tomopyui#12]
In backend.util.center.write_center, need check to ensure that input theta (from ProjectionsBase.angles_rad, which defaults to None) is not None. Otherwise line 32  -- theta = dtype.as_float32(theta) -- will convert theta to "nan", which tomopy recon accepts and  produces garbage images, like this

![Screen Shot 2022-02-04 at 12 05 00 PM](https://user-images.githubusercontent.com/89415472/152595898-37682932-448c-49c0-9da5-74e624df7bf6.png)

**Comment by samwelborn** [comment]
https://github.com/samwelborn/tomopyui/commit/fc415d7c18ecf8d54c86cc2d111a7952d0bf9d44
