### ISSUE TITLE
No such file or directory with TIF import

### ISSUE THREAD

**Issue by DoranPennington** [samwelborn/tomopyui#33]
When importing a TIF stack as prenormalized data, tomopyui reads the data correctly and shows all angles in the import tab, but clicking the "copy data from imported projections" button in the prep tab or attempting to calculate the center of rotation gives this error that there is no file. I've tried trimming .xrm.bim.binprj out of the file names before .tif but it doesn't fix the error. The path in the error code is C:\\Users\\dpenn\\tomopyui\\*.tif but the files are stored in C:\Users\dpenn\Documents\Chemistry\tolbert\alloy_anodes\TXM\20220303_Pennington\BulkSbSn\BulkSbSn2sec1tile_TOMO_220304_051839\RefCorr\croped\BC_croped

Copying the BC_croped folder to the tomopyui directory doesn't work either. Tomopyui writes a folder in the BC_croped directory with two files, import_metadata.json and normalized_projections.hdf5

`
---------------------------------------------------------------------------
UnknownFormatError                        Traceback (most recent call last)
File ~\tomopyui\tomopyui\widgets\center.py:310, in Center.find_center_manual_on_click(self, change)
    302 cen_range = [
    303     self.center_guess - self.search_range,
    304     self.center_guess + self.search_range,
    305     self.search_step,
    306 ]
    308 # reconstruct, but also pull the centers used out to map to center
    309 # textbox
--> 310 self.rec, self.cen_range = write_center(
    311     prj_imgs,
    312     angles_rad,
    313     cen_range=cen_range,
    314     ind=self.index_to_try,
    315     mask=True,
    316     algorithm=self.algorithm,
    317     filter_name=self.filter,
    318     num_iter=self.num_iter,
    319 )
    320 if self.rec is None:
    321     self.find_center_manual_button.button_style = "warning"

File ~\tomopyui\tomopyui\backend\util\center.py:33, in write_center(tomo, theta, cen_range, ind, num_iter, mask, ratio, algorithm, sinogram_order, filter_name)
     30 if theta is None:
     31     return None, cen_range
---> 33 tomo = dtype.as_float32(tomo)
     34 theta = dtype.as_float32(theta)
     36 dt, dy, dx = tomo.shape

File ~\anaconda3\envs\tomopyui-doran\lib\site-packages\tomopy\util\dtype.py:95, in as_float32(arr)
     94 def as_float32(arr):
---> 95     arr = as_ndarray(arr, np.float32)
     96     return as_dtype(arr, np.float32)

File ~\anaconda3\envs\tomopyui-doran\lib\site-packages\tomopy\util\dtype.py:84, in as_ndarray(arr, dtype, copy)
     82 def as_ndarray(arr, dtype=None, copy=False):
     83     if not isinstance(arr, np.ndarray):
---> 84         arr = np.array(arr, dtype=dtype, copy=copy)
     85     return arr

File ~\anaconda3\envs\tomopyui-doran\lib\site-packages\dask\array\core.py:1630, in Array.__array__(self, dtype, **kwargs)
   1629 def __array__(self, dtype=None, **kwargs):
-> 1630     x = self.compute()
   1631     if dtype and x.dtype != dtype:
   1632         x = x.astype(dtype)

File ~\anaconda3\envs\tomopyui-doran\lib\site-packages\dask\base.py:292, in DaskMethodsMixin.compute(self, **kwargs)
    268 def compute(self, **kwargs):
    269     """Compute this dask collection
    270 
    271     This turns a lazy Dask collection into its in-memory equivalent.
   (...)
    290     dask.base.compute
    291     """
--> 292     (result,) = compute(self, traverse=False, **kwargs)
    293     return result

File ~\anaconda3\envs\tomopyui-doran\lib\site-packages\dask\base.py:575, in compute(traverse, optimize_graph, scheduler, get, *args, **kwargs)
    572     keys.append(x.__dask_keys__())
    573     postcomputes.append(x.__dask_postcompute__())
--> 575 results = schedule(dsk, keys, **kwargs)
    576 return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])

File ~\anaconda3\envs\tomopyui-doran\lib\site-packages\dask\threaded.py:81, in get(dsk, result, cache, num_workers, pool, **kwargs)
     78     elif isinstance(pool, multiprocessing.pool.Pool):
     79         pool = MultiprocessingPoolExecutor(pool)
---> 81 results = get_async(
     82     pool.submit,
     83     pool._max_workers,
     84     dsk,
     85     result,
     86     cache=cache,
     87     get_id=_thread_get_id,
     88     pack_exception=pack_exception,
     89     **kwargs,
     90 )
     92 # Cleanup pools associated to dead threads
     93 with pools_lock:

File ~\anaconda3\envs\tomopyui-doran\lib\site-packages\dask\local.py:508, in get_async(submit, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, chunksize, **kwargs)
    506         _execute_task(task, data)  # Re-execute locally
    507     else:
--> 508         raise_exception(exc, tb)
    509 res, worker_id = loads(res_info)
    510 state["cache"][key] = res

File ~\anaconda3\envs\tomopyui-doran\lib\site-packages\dask\local.py:316, in reraise(exc, tb)
    314 if exc.__traceback__ is not tb:
    315     raise exc.with_traceback(tb)
--> 316 raise exc

File ~\anaconda3\envs\tomopyui-doran\lib\site-packages\dask\local.py:221, in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    219 try:
    220     task, data = loads(task_info)
--> 221     result = _execute_task(task, data)
    222     id = get_id()
    223     result = dumps((result, id))

File ~\anaconda3\envs\tomopyui-doran\lib\site-packages\dask\core.py:119, in _execute_task(arg, cache, dsk)
    115     func, args = arg[0], arg[1:]
    116     # Note: Don't assign the subtask results to a variable. numpy detects
    117     # temporaries by their reference count and can execute certain
    118     # operations in-place.
--> 119     return func(*(_execute_task(a, cache) for a in args))
    120 elif not ishashable(arg):
    121     return arg

File ~\anaconda3\envs\tomopyui-doran\lib\site-packages\dask\optimization.py:990, in SubgraphCallable.__call__(self, *args)
    988 if not len(args) == len(self.inkeys):
    989     raise ValueError("Expected %d args, got %d" % (len(self.inkeys), len(args)))
--> 990 return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))

File ~\anaconda3\envs\tomopyui-doran\lib\site-packages\dask\core.py:149, in get(dsk, out, cache)
    147 for key in toposort(dsk):
    148     task = dsk[key]
--> 149     result = _execute_task(task, cache)
    150     cache[key] = result
    151 result = _execute_task(out, cache)

File ~\anaconda3\envs\tomopyui-doran\lib\site-packages\dask\core.py:119, in _execute_task(arg, cache, dsk)
    115     func, args = arg[0], arg[1:]
    116     # Note: Don't assign the subtask results to a variable. numpy detects
    117     # temporaries by their reference count and can execute certain
    118     # operations in-place.
--> 119     return func(*(_execute_task(a, cache) for a in args))
    120 elif not ishashable(arg):
    121     return arg

File ~\anaconda3\envs\tomopyui-doran\lib\site-packages\dask\utils.py:39, in apply(func, args, kwargs)
     37 def apply(func, args, kwargs=None):
     38     if kwargs:
---> 39         return func(*args, **kwargs)
     40     else:
     41         return func(*args)

File ~\anaconda3\envs\tomopyui-doran\lib\site-packages\dask\array\core.py:513, in _pass_extra_kwargs(func, keys, *args, **kwargs)
    506 """Helper for :func:`dask.array.map_blocks` to pass `block_info` or `block_id`.
    507 
    508 For each element of `keys`, a corresponding element of args is changed
    509 to a keyword argument with that key, before all arguments re passed on
    510 to `func`.
    511 """
    512 kwargs.update(zip(keys, args))
--> 513 return func(*args[len(keys) :], **kwargs)

File ~\anaconda3\envs\tomopyui-doran\lib\site-packages\dask_image\imread\__init__.py:99, in _map_read_frame(x, multiple_files, block_info, **kwargs)
     96 else:
     97     i, j = block_info[None]['array-location'][0]
---> 99 return _utils._read_frame(fn=fn, i=slice(i, j), **kwargs)

File ~\anaconda3\envs\tomopyui-doran\lib\site-packages\dask_image\imread\_utils.py:7, in _read_frame(fn, i, arrayfunc)
      6 def _read_frame(fn, i, *, arrayfunc=np.asanyarray):
----> 7     with pims.open(fn) as imgs:
      8         return arrayfunc(imgs[i])

File ~\anaconda3\envs\tomopyui-doran\lib\site-packages\pims\api.py:209, in open(sequence, **kwargs)
    207         warn(message)
    208         exceptions += message + '\n'
--> 209 raise UnknownFormatError("All handlers returned exceptions:\n" + exceptions)

UnknownFormatError: All handlers returned exceptions:
<class 'pims.tiff_stack.TiffStack_tifffile'> errored: [Errno 2] No such file or directory: 'C:\\Users\\dpenn\\tomopyui\\crop_tomo_BulkSbSn2sec1tile_idx00001_-089.00deg.xrm.bim.binprj.tif'
<class 'pims.imageio_reader.ImageIOReader'> errored: The ImageIOReader requires imageio and (for imageio >= 2.5) imageio-ffmpeg to work.
<class 'pims.bioformats.BioformatsReader'> errored: The file "crop_tomo_BulkSbSn2sec1tile_idx00001_-089.00deg.xrm.bim.binprj.tif" does not exist.
`

**Comment by samwelborn** [comment]
You have to press the "import prenormalized projections" button at the top of the other screens (in prep, center, alignment, and recon). that will activate the imported projections.
