### ISSUE TITLE
unable to import .xrm

### ISSUE THREAD

**Issue by DoranPennington** [samwelborn/tomopyui#34]
This is the same dataset as the other one giving me issues. When trying to import .xrm instead of .tif, I get an error "IndexError: List index is out of range". The files are named as follows in the directory C:\Users\dpenn\Documents\Chemistry\tolbert\alloy_anodes\TXM\20220303_Pennington\BulkSbSn\BulkSbSn2sec1tile_TOMO_220304_051839

ScanInfo_BulkSbSn2sec1tile_220304_051839.txt
ref_BulkSbSn2sec1tile_idx00000_+000.00deg_img001of010.xrm which goes to 10
tomo_BulkSbSn2sec1tile_idx00000_-090.00deg.xrm which goes from index 0 to 179 and angle -90 to +89

here is the error message

`
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
File ~\tomopyui\tomopyui\widgets\helpers.py:336, in ImportButton.run_callback(self, *args)
    334 self.button.icon = self.icon_during
    335 self.button.description = self.description_during
--> 336 self.callback()
    337 self.button.button_style = self.button_style_after
    338 self.button.icon = self.icon_after

File ~\tomopyui\tomopyui\widgets\imports.py:1369, in RawUploader_SSRL62C.import_data(self)
   1366 def import_data(self):
   1368     tic = time.perf_counter()
-> 1369     self.projections.import_filedir_all(self)
   1370     toc = time.perf_counter()
   1371     self.projections.status_label.value = (
   1372         f"Import and normalization took {toc-tic:.0f}s"
   1373     )

File ~\tomopyui\tomopyui\backend\io.py:921, in RawProjectionsXRM_SSRL62C.import_filedir_all(self, Uploader)
    917     self.selected_energies = (Uploader.energy_select_multiple.options[0],)
    918     Uploader.energy_select_multiple.value = (
    919         Uploader.energy_select_multiple.options[0],
    920     )
--> 921 self.import_from_run_script(Uploader)
    922 self.imported = True

File ~\tomopyui\tomopyui\backend\io.py:1245, in RawProjectionsXRM_SSRL62C.import_from_run_script(self, Uploader)
   1243 self.flats_ind_from_collect(collect)
   1244 self.status_label.value = "Normalizing."
-> 1245 self._data = RawProjectionsBase.normalize_and_average(
   1246     projs,
   1247     flats,
   1248     darks,
   1249     self.flats_ind,
   1250     self.scan_info["NEXPOSURES"],
   1251     status_label=self.status_label,
   1252     compute=False,
   1253 )
   1254 self.data = self._data
   1256 self.status_label.value = "Saving projections as .npy for faster IO."

File ~\tomopyui\tomopyui\backend\io.py:715, in RawProjectionsBase.normalize_and_average(projs, flats, dark, flat_loc, num_exposures_per_proj, status_label, compute)
    706 # Projection locations defined as the centerpoint between two reference
    707 # collections
    708 # Chunk the projections such that they will be divided by the nearest flat
    709 # The first chunk of data will be divided by the first flat.
    710 # The first chunk of data is likely smaller than the others.
    711 proj_locations = [
    712     int(np.ceil((flat_loc[i] + flat_loc[i + 1]) / 2))
    713     for i in range(len(flat_loc) - 1)
    714 ]
--> 715 chunk_setup = [int(np.ceil(proj_locations[0]))]
    716 for i in range(len(proj_locations) - 1):
    717     chunk_setup.append(proj_locations[i + 1] - proj_locations[i])

IndexError: list index out of range
`

**Comment by samwelborn** [comment]
fixed with https://github.com/samwelborn/tomopyui/commit/1ca72d60d9d2008e09661dbdd988820a56fb1c5a

let me know if that didn't work for you
