### ISSUE TITLE
Loading status indicator for imports tab

### ISSUE THREAD

**Issue by perlmutter** [samwelborn/tomopyui#4]
Make big teal button say “load data” or something (instead of “null”). Can there be a flashing light or  progress bar or something to indicate data is loading. It can be hard to tell what’s going on when you switch datasets (especially if they’re big)
<img width="616" alt="Screen Shot 2022-02-01 at 2 55 38 PM" src="https://user-images.githubusercontent.com/89415472/152065260-4f04df74-66eb-4b62-b45c-0698bfbe14fb.png">
.

**Comment by samwelborn** [comment]
https://github.com/samwelborn/tomopyui/commit/f8a49102ed8b7719b575ddd75bf622f878bb2ced
