### ISSUE TITLE
Viewing skewed aspect ratio images in import tab

### ISSUE THREAD

**Issue by perlmutter** [samwelborn/tomopyui#6]
Need better way to view data skewed aspect ratio (eg. when switching to sinogram). Currently, it looks like image width is held constant, and length is allowed to be as long as necessary to keep aspect ratio 1-to-1. Probably better to have a max length, and start changing the aspect ratio of images that would otherwise exceed that length. Maybe a control knob of some sort would be helpful too, not sure.
![Screen Shot 2022-02-01 at 11 36 12 AM](https://user-images.githubusercontent.com/89415472/152066098-0310fd82-5753-4375-8fdb-5f0ce8c810d4.png)
.

**Comment by samwelborn** [comment]
https://github.com/samwelborn/tomopyui/commit/5b2f205f0f5d9007b157a89b9d14876d94dc512c

I think this is at least a temporary fix to this. One thing I worry about is the figure scale changing such that the `BrushSelector` ends up not giving the correct values. 

Going to work on handling the brushselector later anyway, so I'll close this.
